<?php

namespace Esecouristes\SectionBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AgrementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgrementRepository extends EntityRepository
{
}
