<?php

namespace Esecouristes\SectionBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SectionAgrementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SectionAgrementRepository extends EntityRepository
{
}
