parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: esecouristes-v2
    database_user: root
    database_password: 'b2Emi0902*'
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: e1f29909ef649f7dbd438cb9ba5103ed2
    database_path: null
