security:
    encoders:
        Esecouristes\UserBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main_login:
            pattern:   ^/login$
            anonymous: true

        main:
            pattern:   ^/
            anonymous: false
            provider:  main
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                always_use_default_target_path: true
                default_target_path: /sections
            logout:
                path:    fos_user_security_logout
                target:  /login
            remember_me:
                key:     %secret%

    access_control:
        - { path: /sections/ajouter, roles: ROLE_ADMIN }
        - { path: ^/sections/modifier, roles: ROLE_ADMIN }
        - { path: ^/sections/supprimer, roles: ROLE_ADMIN }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
