parameters:
#    esecouristes_user.example.class: Esecouristes\UserBundle\Example

services:
#    esecouristes_user.example:
#        class: %esecouristes_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
