ALTER TABLE `type_materiel` ADD `TM_CONTROLE` BOOLEAN NOT NULL DEFAULT '0',
ADD `TM_PERIODE_CONTROLE` VARCHAR( 255 ) NULL DEFAULT NULL;

CREATE TABLE `ebrigade2`.`materiel_controle` (
`MA_ID` INT( 11 ) NOT NULL ,
`MAC_CONTROLED_BY` INT( 11 ) NOT NULL ,
`MAC_COMMENT` VARCHAR( 60 ) NULL DEFAULT NULL ,
`MAC_CONTROLE_DATE` DATE NOT NULL ,
`MAC_TYPE` VARCHAR( 42 ) NOT NULL ,
`MAC_ID` INT( 11 ) NOT NULL AUTO_INCREMENT ,
PRIMARY KEY ( `MAC_ID` );
